The search feature
aman-can/rootShoot-react pull request #9
Opened 2022-03-26 15:39 UTC by aman-can

Added the search feature from across the web

2022-03-26 17:23 UTC, shobit1337 requested changes
Gave some suggestions. Please go through them once.

2022-03-26 17:23 UTC, shobit1337 commented on src/components/Navbar/Navbar.jsx
> +                            if (e.target.value === "") {
Move this logic part to a separate function, It will look better.

2022-03-26 17:23 UTC, shobit1337 commented on src/components/Navbar/navbar.css
> +    /* max-height: 150px; */
You should remove unnecessary comments before pushing code to GitHub

2022-03-26 17:23 UTC, shobit1337 commented on src/hooks/useLockBodyScroll.js
> +// 9063295041 naveen
What's this? 😂

2022-03-26 17:36 UTC, shraddha-1402 approved these changes
Liked the ui of the search results 
The use of CSS variables for transition and app bar was great
Good work!

2022-03-26 17:36 UTC, shraddha-1402 commented on src/components/Navbar/Navbar.jsx
>                                  to="/products"
suggestion: would be good if you make constant variables for routes

2022-03-26 17:36 UTC, shraddha-1402 commented on src/reducers/filterReducer.js
> +        case "SEARCH_TEXT":
suggestion: case values can also be used from constant variables

2022-03-26 18:19 UTC, rutvikpumak approved these changes
Added some comments and rest of the code looks code

2022-03-26 18:19 UTC, rutvikpumak commented on src/components/Navbar/Navbar.jsx
> +                        onKeyUp={(e) => {
never write a lot of functions in jsx. Bad practise

2022-03-27 05:09 UTC, shobit1337 approved these changes

2022-03-28 10:09 UTC, merged